apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: oss-

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    # version: 14.3.0
    releaseName: prometheus-demo
    # valuesFile: values.yaml
    

helmGlobals:
  chartHome: ../../charts

# resources:
# - namespace.yml

# https://github.com/kubernetes-sigs/kustomize/issues/4401