apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

labels:
  - pairs:
      env: dev
      owned-by: team-a


resources:
  - adservice
  - cartservice
  - checkoutservice
  - currencyservice
  - frontend
  - recommendationservice
  - shippingservice
  - paymentservice
  - productcatalogservice
  - loadgenerator
  - namespace.yml