apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

nameSuffix: -dev

# commonLabels:
#   env: dev
#   owned-by: team-a

labels:
  - pairs:
      env: dev
      owned-by: team-a

resources:
  - "../../../bases/base1"
  - namespace.yml