apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

nameSuffix: -staging

# commonLabels:
#   env: staging
#   owned-by: team-a

labels:
  - pairs:
      env: staging
      owned-by: team-a

replicas:
- name: adservice
  count: 3

resources:
  - "../../../bases/base1"
  - namespace.yml